// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenPlay_screen_init(void)
{
    ui_ScreenPlay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg = lv_img_create(ui_ScreenPlay);
    lv_img_set_src(ui_bg, &ui_img_app_bg_png);
    lv_obj_set_width(ui_bg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopLabel = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_TopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TopLabel, 31);
    lv_obj_set_y(ui_TopLabel, -220);
    lv_obj_set_align(ui_TopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TopLabel, "LED Demo");
    lv_obj_set_style_text_color(ui_TopLabel, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TopLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrpSwitches = lv_obj_create(ui_ScreenPlay);
    lv_obj_remove_style_all(ui_GrpSwitches);
    lv_obj_set_width(ui_GrpSwitches, 114);
    lv_obj_set_height(ui_GrpSwitches, 222);
    lv_obj_set_x(ui_GrpSwitches, 298);
    lv_obj_set_y(ui_GrpSwitches, -50);
    lv_obj_set_align(ui_GrpSwitches, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GrpSwitches, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_GrpSwitches);
    lv_obj_set_width(ui_Switch1, 75);
    lv_obj_set_height(ui_Switch1, 35);
    lv_obj_set_x(ui_Switch1, 0);
    lv_obj_set_y(ui_Switch1, -70);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x3E3D3D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x93A8FE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch1, lv_color_hex(0x0A3A91), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch1, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch1, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch1, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch1, -5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_GrpSwitches);
    lv_obj_set_width(ui_Switch2, 75);
    lv_obj_set_height(ui_Switch2, 35);
    lv_obj_set_x(ui_Switch2, 0);
    lv_obj_set_y(ui_Switch2, 70);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x3E3D3D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x93A8FE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch2, lv_color_hex(0x0A3A91), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch2, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_GrpSwitches);
    lv_obj_set_width(ui_Switch4, 75);
    lv_obj_set_height(ui_Switch4, 35);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x3E3D3D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch4, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x93A8FE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch4, lv_color_hex(0x0A3A91), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch4, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelEfWave = lv_label_create(ui_GrpSwitches);
    lv_obj_set_width(ui_LabelEfWave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEfWave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEfWave, 0);
    lv_obj_set_y(ui_LabelEfWave, -31);
    lv_obj_set_align(ui_LabelEfWave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEfWave, "Wave");
    lv_obj_set_style_text_color(ui_LabelEfWave, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEfWave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEfFlow = lv_label_create(ui_GrpSwitches);
    lv_obj_set_width(ui_LabelEfFlow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEfFlow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEfFlow, 1);
    lv_obj_set_y(ui_LabelEfFlow, 40);
    lv_obj_set_align(ui_LabelEfFlow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEfFlow, "Flow");
    lv_obj_set_style_text_color(ui_LabelEfFlow, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEfFlow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEfPulse = lv_label_create(ui_GrpSwitches);
    lv_obj_set_width(ui_LabelEfPulse, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEfPulse, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEfPulse, 1);
    lv_obj_set_y(ui_LabelEfPulse, -101);
    lv_obj_set_align(ui_LabelEfPulse, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEfPulse, "Pulse");
    lv_obj_set_style_text_color(ui_LabelEfPulse, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEfPulse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrpColors = lv_obj_create(ui_ScreenPlay);
    lv_obj_remove_style_all(ui_GrpColors);
    lv_obj_set_width(ui_GrpColors, 500);
    lv_obj_set_height(ui_GrpColors, 260);
    lv_obj_set_x(ui_GrpColors, -44);
    lv_obj_set_y(ui_GrpColors, -34);
    lv_obj_set_align(ui_GrpColors, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GrpColors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderClrRight = lv_slider_create(ui_GrpColors);
    lv_obj_set_width(ui_SliderClrRight, 42);
    lv_obj_set_height(ui_SliderClrRight, 221);
    lv_obj_set_x(ui_SliderClrRight, 155);
    lv_obj_set_y(ui_SliderClrRight, 12);
    lv_obj_set_align(ui_SliderClrRight, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderClrRight, lv_color_hex(0x363434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderClrRight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderClrRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderClrRight, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrRight, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrRight, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrRight, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrRight, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrRight, lv_color_hex(0x93A8FE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrRight, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderClrRight, lv_color_hex(0x0A3A91), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderClrRight, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderClrRight, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderClrRight, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderClrRight, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderClrRight, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SliderClrRight, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SliderClrRight, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrRight, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrRight, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrRight, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrRight, -7, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderClrLeft = lv_slider_create(ui_GrpColors);
    lv_obj_set_width(ui_SliderClrLeft, 42);
    lv_obj_set_height(ui_SliderClrLeft, 221);
    lv_obj_set_x(ui_SliderClrLeft, -155);
    lv_obj_set_y(ui_SliderClrLeft, 12);
    lv_obj_set_align(ui_SliderClrLeft, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderClrLeft, lv_color_hex(0x363434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderClrLeft, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderClrLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderClrLeft, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrLeft, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrLeft, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrLeft, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrLeft, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrLeft, lv_color_hex(0x93A8FE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrLeft, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderClrLeft, lv_color_hex(0x0A3A91), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderClrLeft, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderClrLeft, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderClrLeft, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderClrLeft, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderClrLeft, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SliderClrLeft, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SliderClrLeft, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrLeft, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrLeft, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrLeft, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrLeft, -7, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderClrCenter = lv_slider_create(ui_GrpColors);
    lv_obj_set_width(ui_SliderClrCenter, 42);
    lv_obj_set_height(ui_SliderClrCenter, 221);
    lv_obj_set_x(ui_SliderClrCenter, 0);
    lv_obj_set_y(ui_SliderClrCenter, 12);
    lv_obj_set_align(ui_SliderClrCenter, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderClrCenter, lv_color_hex(0x363434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrCenter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderClrCenter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderClrCenter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderClrCenter, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrCenter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrCenter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrCenter, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrCenter, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrCenter, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrCenter, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrCenter, lv_color_hex(0x93A8FE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrCenter, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderClrCenter, lv_color_hex(0x0A3A91), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderClrCenter, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderClrCenter, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderClrCenter, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderClrCenter, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderClrCenter, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SliderClrCenter, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SliderClrCenter, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrCenter, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrCenter, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrCenter, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrCenter, -7, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelLeft = lv_label_create(ui_GrpColors);
    lv_obj_set_width(ui_LabelLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLeft, -155);
    lv_obj_set_y(ui_LabelLeft, -118);
    lv_obj_set_align(ui_LabelLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLeft, "LEFT");
    lv_obj_set_style_text_color(ui_LabelLeft, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCenter = lv_label_create(ui_GrpColors);
    lv_obj_set_width(ui_LabelCenter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCenter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCenter, -3);
    lv_obj_set_y(ui_LabelCenter, -118);
    lv_obj_set_align(ui_LabelCenter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCenter, "CENTER");
    lv_obj_set_style_text_color(ui_LabelCenter, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCenter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRight = lv_label_create(ui_GrpColors);
    lv_obj_set_width(ui_LabelRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRight, 155);
    lv_obj_set_y(ui_LabelRight, -118);
    lv_obj_set_align(ui_LabelRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRight, "RIGHT");
    lv_obj_set_style_text_color(ui_LabelRight, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_GrpColors);
    lv_img_set_src(ui_Image1, &ui_img_color_bar_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -77);
    lv_obj_set_y(ui_Image1, 12);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_GrpColors);
    lv_img_set_src(ui_Image4, &ui_img_color_bar_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 78);
    lv_obj_set_y(ui_Image4, 12);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_GrpColors);
    lv_img_set_src(ui_Image5, &ui_img_color_bar_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -226);
    lv_obj_set_y(ui_Image5, 12);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_GrpColors);
    lv_img_set_src(ui_Image7, &ui_img_color_bar_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 229);
    lv_obj_set_y(ui_Image7, 12);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnStart = lv_imgbtn_create(ui_ScreenPlay);
    lv_imgbtn_set_src(ui_BtnStart, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_play_inact_png, NULL);
    lv_imgbtn_set_src(ui_BtnStart, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_play_act_png, NULL);
    lv_imgbtn_set_src(ui_BtnStart, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_play_inact_png, NULL);
    lv_imgbtn_set_src(ui_BtnStart, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_play_act_png, NULL);
    lv_imgbtn_set_src(ui_BtnStart, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_play_act_png, NULL);
    lv_imgbtn_set_src(ui_BtnStart, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_play_inact_png, NULL);
    lv_obj_set_height(ui_BtnStart, 146);
    lv_obj_set_width(ui_BtnStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BtnStart, 298);
    lv_obj_set_y(ui_BtnStart, 156);
    lv_obj_set_align(ui_BtnStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnStart, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_BtnStart, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_BtnStart, LV_SCROLLBAR_MODE_OFF);

    ui_Label1 = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 298);
    lv_obj_set_y(ui_Label1, 78);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Play");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrpDynamics = lv_obj_create(ui_ScreenPlay);
    lv_obj_remove_style_all(ui_GrpDynamics);
    lv_obj_set_width(ui_GrpDynamics, 522);
    lv_obj_set_height(ui_GrpDynamics, 71);
    lv_obj_set_x(ui_GrpDynamics, -37);
    lv_obj_set_y(ui_GrpDynamics, 166);
    lv_obj_set_align(ui_GrpDynamics, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GrpDynamics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderClrVolume = lv_slider_create(ui_GrpDynamics);
    lv_obj_set_width(ui_SliderClrVolume, 200);
    lv_obj_set_height(ui_SliderClrVolume, 42);
    lv_obj_set_x(ui_SliderClrVolume, -120);
    lv_obj_set_y(ui_SliderClrVolume, 12);
    lv_obj_set_align(ui_SliderClrVolume, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderClrVolume, lv_color_hex(0x363434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderClrVolume, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderClrVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderClrVolume, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrVolume, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrVolume, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrVolume, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrVolume, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrVolume, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrVolume, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrVolume, lv_color_hex(0x93A8FE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrVolume, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderClrVolume, lv_color_hex(0x0A3A91), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderClrVolume, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderClrVolume, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderClrVolume, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderClrVolume, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderClrVolume, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SliderClrVolume, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SliderClrVolume, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrVolume, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrVolume, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrVolume, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrVolume, -7, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderClrSpeed = lv_slider_create(ui_GrpDynamics);
    lv_obj_set_width(ui_SliderClrSpeed, 200);
    lv_obj_set_height(ui_SliderClrSpeed, 42);
    lv_obj_set_x(ui_SliderClrSpeed, 120);
    lv_obj_set_y(ui_SliderClrSpeed, 12);
    lv_obj_set_align(ui_SliderClrSpeed, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderClrSpeed, lv_color_hex(0x363434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderClrSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderClrSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderClrSpeed, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrSpeed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrSpeed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrSpeed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrSpeed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrSpeed, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrSpeed, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderClrSpeed, lv_color_hex(0x93A8FE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderClrSpeed, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderClrSpeed, lv_color_hex(0x0A3A91), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderClrSpeed, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderClrSpeed, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderClrSpeed, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderClrSpeed, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderClrSpeed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SliderClrSpeed, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SliderClrSpeed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderClrSpeed, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderClrSpeed, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderClrSpeed, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderClrSpeed, -7, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelVolume = lv_label_create(ui_GrpDynamics);
    lv_obj_set_width(ui_LabelVolume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVolume, 101);
    lv_obj_set_y(ui_LabelVolume, -25);
    lv_obj_set_align(ui_LabelVolume, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelVolume, "VOLUME: 0");
    lv_obj_set_style_text_color(ui_LabelVolume, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeed = lv_label_create(ui_GrpDynamics);
    lv_obj_set_width(ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed, 356);
    lv_obj_set_y(ui_LabelSpeed, -25);
    lv_obj_set_align(ui_LabelSpeed, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelSpeed, "SPEED: 0");
    lv_obj_set_style_text_color(ui_LabelSpeed, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelColours = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_LabelColours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColours, -46);
    lv_obj_set_y(ui_LabelColours, -181);
    lv_obj_set_align(ui_LabelColours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColours, "Colours");
    lv_obj_set_style_text_color(ui_LabelColours, lv_color_hex(0x9793CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgFrameTopLeft = lv_img_create(ui_ScreenPlay);
    lv_img_set_src(ui_ImgFrameTopLeft, &ui_img_frame_left_png);
    lv_obj_set_width(ui_ImgFrameTopLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgFrameTopLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgFrameTopLeft, -157);
    lv_obj_set_y(ui_ImgFrameTopLeft, -178);
    lv_obj_set_align(ui_ImgFrameTopLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgFrameTopLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgFrameTopLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgFrameTopRight = lv_img_create(ui_ScreenPlay);
    lv_img_set_src(ui_ImgFrameTopRight, &ui_img_frame_right_png);
    lv_obj_set_width(ui_ImgFrameTopRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgFrameTopRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgFrameTopRight, 67);
    lv_obj_set_y(ui_ImgFrameTopRight, -178);
    lv_obj_set_align(ui_ImgFrameTopRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgFrameTopRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgFrameTopRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDynamics = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_LabelDynamics, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDynamics, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDynamics, -41);
    lv_obj_set_y(ui_LabelDynamics, 110);
    lv_obj_set_align(ui_LabelDynamics, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDynamics, "Dynamics");
    lv_obj_set_style_text_color(ui_LabelDynamics, lv_color_hex(0x9793CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDynamics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerFrameBotLeft = lv_obj_create(ui_ScreenPlay);
    lv_obj_remove_style_all(ui_ContainerFrameBotLeft);
    lv_obj_set_width(ui_ContainerFrameBotLeft, 62);
    lv_obj_set_height(ui_ContainerFrameBotLeft, 23);
    lv_obj_set_x(ui_ContainerFrameBotLeft, -144);
    lv_obj_set_y(ui_ContainerFrameBotLeft, 111);
    lv_obj_set_align(ui_ContainerFrameBotLeft, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerFrameBotLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgFrameBottomLeft = lv_img_create(ui_ContainerFrameBotLeft);
    lv_img_set_src(ui_ImgFrameBottomLeft, &ui_img_frame_left_png);
    lv_obj_set_width(ui_ImgFrameBottomLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgFrameBottomLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgFrameBottomLeft, 21);
    lv_obj_set_y(ui_ImgFrameBottomLeft, 6);
    lv_obj_set_align(ui_ImgFrameBottomLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgFrameBottomLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgFrameBottomLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerFrameBotRight = lv_obj_create(ui_ScreenPlay);
    lv_obj_remove_style_all(ui_ContainerFrameBotRight);
    lv_obj_set_width(ui_ContainerFrameBotRight, 62);
    lv_obj_set_height(ui_ContainerFrameBotRight, 23);
    lv_obj_set_x(ui_ContainerFrameBotRight, 62);
    lv_obj_set_y(ui_ContainerFrameBotRight, 111);
    lv_obj_set_align(ui_ContainerFrameBotRight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerFrameBotRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgFrameBottomRight = lv_img_create(ui_ContainerFrameBotRight);
    lv_img_set_src(ui_ImgFrameBottomRight, &ui_img_frame_right_png);
    lv_obj_set_width(ui_ImgFrameBottomRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgFrameBottomRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgFrameBottomRight, -17);
    lv_obj_set_y(ui_ImgFrameBottomRight, 6);
    lv_obj_set_align(ui_ImgFrameBottomRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgFrameBottomRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgFrameBottomRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelFX = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_LabelFX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFX, 297);
    lv_obj_set_y(ui_LabelFX, -181);
    lv_obj_set_align(ui_LabelFX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFX, "FX");
    lv_obj_set_style_text_color(ui_LabelFX, lv_color_hex(0x9793CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerFrameBotLeft1 = lv_obj_create(ui_ScreenPlay);
    lv_obj_remove_style_all(ui_ContainerFrameBotLeft1);
    lv_obj_set_width(ui_ContainerFrameBotLeft1, 21);
    lv_obj_set_height(ui_ContainerFrameBotLeft1, 23);
    lv_obj_set_x(ui_ContainerFrameBotLeft1, 268);
    lv_obj_set_y(ui_ContainerFrameBotLeft1, -180);
    lv_obj_set_align(ui_ContainerFrameBotLeft1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerFrameBotLeft1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgFrameBottomLeft1 = lv_img_create(ui_ContainerFrameBotLeft1);
    lv_img_set_src(ui_ImgFrameBottomLeft1, &ui_img_frame_left_png);
    lv_obj_set_width(ui_ImgFrameBottomLeft1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgFrameBottomLeft1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgFrameBottomLeft1, 40);
    lv_obj_set_y(ui_ImgFrameBottomLeft1, 4);
    lv_obj_set_align(ui_ImgFrameBottomLeft1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgFrameBottomLeft1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgFrameBottomLeft1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerFrameBotRight1 = lv_obj_create(ui_ScreenPlay);
    lv_obj_remove_style_all(ui_ContainerFrameBotRight1);
    lv_obj_set_width(ui_ContainerFrameBotRight1, 21);
    lv_obj_set_height(ui_ContainerFrameBotRight1, 23);
    lv_obj_set_x(ui_ContainerFrameBotRight1, 326);
    lv_obj_set_y(ui_ContainerFrameBotRight1, -180);
    lv_obj_set_align(ui_ContainerFrameBotRight1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerFrameBotRight1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgFrameBottomRight1 = lv_img_create(ui_ContainerFrameBotRight1);
    lv_img_set_src(ui_ImgFrameBottomRight1, &ui_img_frame_right_png);
    lv_obj_set_width(ui_ImgFrameBottomRight1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgFrameBottomRight1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgFrameBottomRight1, -38);
    lv_obj_set_y(ui_ImgFrameBottomRight1, 4);
    lv_obj_set_align(ui_ImgFrameBottomRight1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgFrameBottomRight1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgFrameBottomRight1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageMenuPlayS1 = lv_img_create(ui_ScreenPlay);
    lv_img_set_src(ui_ImageMenuPlayS1, &ui_img_menu_play_on_png);
    lv_obj_set_width(ui_ImageMenuPlayS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageMenuPlayS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageMenuPlayS1, -355);
    lv_obj_set_y(ui_ImageMenuPlayS1, -104);
    lv_obj_set_align(ui_ImageMenuPlayS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMenuPlayS1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMenuPlayS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_ScreenPlay);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 79);
    lv_obj_set_height(ui_Container1, 154);
    lv_obj_set_x(ui_Container1, -359);
    lv_obj_set_y(ui_Container1, 83);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderClrRight, ui_event_SliderClrRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderClrLeft, ui_event_SliderClrLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderClrCenter, ui_event_SliderClrCenter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnStart, ui_event_BtnStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderClrVolume, ui_event_SliderClrVolume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderClrSpeed, ui_event_SliderClrSpeed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container1, ui_event_Container1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPlay, ui_event_ScreenPlay, LV_EVENT_ALL, NULL);

}
