// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSetup_screen_init(void)
{
    ui_ScreenSetup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBG = lv_img_create(ui_ScreenSetup);
    lv_img_set_src(ui_ImageBG, &ui_img_app_bg_png);
    lv_obj_set_width(ui_ImageBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnExit = lv_imgbtn_create(ui_ScreenSetup);
    lv_imgbtn_set_src(ui_BtnExit, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BtnExit, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BtnExit, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BtnExit, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BtnExit, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BtnExit, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_obj_set_height(ui_BtnExit, 64);
    lv_obj_set_width(ui_BtnExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BtnExit, 19);
    lv_obj_set_y(ui_BtnExit, 180);
    lv_obj_set_align(ui_BtnExit, LV_ALIGN_CENTER);

    ui_LabelReboot = lv_label_create(ui_BtnExit);
    lv_obj_set_width(ui_LabelReboot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReboot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelReboot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReboot, "REBOOT");
    lv_label_set_recolor(ui_LabelReboot, "true");
    lv_obj_set_style_text_color(ui_LabelReboot, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelReboot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInfo = lv_obj_create(ui_ScreenSetup);
    lv_obj_set_width(ui_PanelInfo, 599);
    lv_obj_set_height(ui_PanelInfo, 318);
    lv_obj_set_x(ui_PanelInfo, 32);
    lv_obj_set_y(ui_PanelInfo, -21);
    lv_obj_set_align(ui_PanelInfo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelInfo, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelInfo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInfoText = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_LabelInfoText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInfoText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelInfoText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInfoText,
                      "#FFFFFF BCT LED Demo# v.0.1\n----------------------------------------------------------------------------------------------------------\nThe UI of this application was created in #40B0FF SquareLine Studio# editor.\n\n* the graphics uses Linux frame buffer and LVGL library to render  the UI\n* the touch screen is controled by TSLib library\n* the addressable #FF8080 R##80FF80 G##8080FF B# LED chain is controlled via SPI interface \n* it runs on a smal Linux system produced by Buildroot\n\n#FFFFFF Controls:#\n* #40B0FF Left Center# and #40B0FF Right# colour sliders change the colours of the respective \n  LED chain sections.\n* #40B0FF Volume# slider adjusts the width of each colour section.\n* #40B0FF Speed #slider changes the animation speed of the effects.\n* #40B0FF FX# switches apply animation effects.\n\nFeel free to interact with the demo, or press the #FFFFFF REBOOT# button\nto check the system start-up speed.");
    lv_label_set_recolor(ui_LabelInfoText, "true");
    lv_obj_set_style_text_color(ui_LabelInfoText, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelInfoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopLabel2 = lv_label_create(ui_ScreenSetup);
    lv_obj_set_width(ui_TopLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TopLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TopLabel2, 31);
    lv_obj_set_y(ui_TopLabel2, -220);
    lv_obj_set_align(ui_TopLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TopLabel2, "LED Demo");
    lv_obj_set_style_text_color(ui_TopLabel2, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TopLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageMenuSetupS2 = lv_img_create(ui_ScreenSetup);
    lv_img_set_src(ui_ImageMenuSetupS2, &ui_img_menu_setup_on_png);
    lv_obj_set_width(ui_ImageMenuSetupS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageMenuSetupS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageMenuSetupS2, -355);
    lv_obj_set_y(ui_ImageMenuSetupS2, 92);
    lv_obj_set_align(ui_ImageMenuSetupS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMenuSetupS2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMenuSetupS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerMenuPlayS2 = lv_obj_create(ui_ScreenSetup);
    lv_obj_remove_style_all(ui_ContainerMenuPlayS2);
    lv_obj_set_width(ui_ContainerMenuPlayS2, 80);
    lv_obj_set_height(ui_ContainerMenuPlayS2, 150);
    lv_obj_set_x(ui_ContainerMenuPlayS2, -357);
    lv_obj_set_y(ui_ContainerMenuPlayS2, -101);
    lv_obj_set_align(ui_ContainerMenuPlayS2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMenuPlayS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BtnExit, ui_event_BtnExit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerMenuPlayS2, ui_event_ContainerMenuPlayS2, LV_EVENT_ALL, NULL);

}
