// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenPlay
void ui_ScreenPlay_screen_init(void);
void ui_event_ScreenPlay(lv_event_t * e);
lv_obj_t * ui_ScreenPlay;
lv_obj_t * ui_bg;
lv_obj_t * ui_TopLabel;
lv_obj_t * ui_GrpSwitches;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
void ui_event_Switch4(lv_event_t * e);
lv_obj_t * ui_Switch4;
lv_obj_t * ui_LabelEfWave;
lv_obj_t * ui_LabelEfFlow;
lv_obj_t * ui_LabelEfPulse;
lv_obj_t * ui_GrpColors;
void ui_event_SliderClrRight(lv_event_t * e);
lv_obj_t * ui_SliderClrRight;
void ui_event_SliderClrLeft(lv_event_t * e);
lv_obj_t * ui_SliderClrLeft;
void ui_event_SliderClrCenter(lv_event_t * e);
lv_obj_t * ui_SliderClrCenter;
lv_obj_t * ui_LabelLeft;
lv_obj_t * ui_LabelCenter;
lv_obj_t * ui_LabelRight;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image7;
void ui_event_BtnStart(lv_event_t * e);
lv_obj_t * ui_BtnStart;
lv_obj_t * ui_Label1;
lv_obj_t * ui_GrpDynamics;
void ui_event_SliderClrVolume(lv_event_t * e);
lv_obj_t * ui_SliderClrVolume;
void ui_event_SliderClrSpeed(lv_event_t * e);
lv_obj_t * ui_SliderClrSpeed;
lv_obj_t * ui_LabelVolume;
lv_obj_t * ui_LabelSpeed;
lv_obj_t * ui_LabelColours;
lv_obj_t * ui_ImgFrameTopLeft;
lv_obj_t * ui_ImgFrameTopRight;
lv_obj_t * ui_LabelDynamics;
lv_obj_t * ui_ContainerFrameBotLeft;
lv_obj_t * ui_ImgFrameBottomLeft;
lv_obj_t * ui_ContainerFrameBotRight;
lv_obj_t * ui_ImgFrameBottomRight;
lv_obj_t * ui_LabelFX;
lv_obj_t * ui_ContainerFrameBotLeft1;
lv_obj_t * ui_ImgFrameBottomLeft1;
lv_obj_t * ui_ContainerFrameBotRight1;
lv_obj_t * ui_ImgFrameBottomRight1;
lv_obj_t * ui_ImageMenuPlayS1;
void ui_event_Container1(lv_event_t * e);
lv_obj_t * ui_Container1;


// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
lv_obj_t * ui_ScreenSetup;
lv_obj_t * ui_ImageBG;
void ui_event_BtnExit(lv_event_t * e);
lv_obj_t * ui_BtnExit;
lv_obj_t * ui_LabelReboot;
lv_obj_t * ui_PanelInfo;
lv_obj_t * ui_LabelInfoText;
lv_obj_t * ui_TopLabel2;
lv_obj_t * ui_ImageMenuSetupS2;
void ui_event_ContainerMenuPlayS2(lv_event_t * e);
lv_obj_t * ui_ContainerMenuPlayS2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScrPlayInit(e);
    }
}
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        EvPulseOn(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        EvPulseOff(e);
    }
}
void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        EvFlowOn(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        EvFlowOff(e);
    }
}
void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        EvWaveOn(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        EvWaveOff(e);
    }
}
void ui_event_SliderClrRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        EvRightChanged(e);
    }
}
void ui_event_SliderClrLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        EvLeftChanged(e);
    }
}
void ui_event_SliderClrCenter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        EvCenterChanged(e);
    }
}
void ui_event_BtnStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        EvPlayOn(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        EvPlayOff(e);
    }
}
void ui_event_SliderClrVolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        EvVolumeChanged(e);
        _ui_slider_set_text_value(ui_LabelVolume, target, "VOLUME: ", "");
    }
}
void ui_event_SliderClrSpeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        EvSpeedChanged(e);
        _ui_slider_set_text_value(ui_LabelSpeed, target, "SPEED: ", "");
    }
}
void ui_event_Container1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSetup, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenSetup_screen_init);
    }
}
void ui_event_BtnExit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        EventRebootClicked(e);
    }
}
void ui_event_ContainerMenuPlayS2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPlay, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenPlay_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenPlay_screen_init();
    ui_ScreenSetup_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenPlay);
}
