// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenPlay
void ui_ScreenPlay_screen_init(void);
void ui_event_ScreenPlay(lv_event_t * e);
extern lv_obj_t * ui_ScreenPlay;
extern lv_obj_t * ui_bg;
extern lv_obj_t * ui_TopLabel;
extern lv_obj_t * ui_GrpSwitches;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_LabelEfWave;
extern lv_obj_t * ui_LabelEfFlow;
extern lv_obj_t * ui_LabelEfPulse;
extern lv_obj_t * ui_GrpColors;
void ui_event_SliderClrRight(lv_event_t * e);
extern lv_obj_t * ui_SliderClrRight;
void ui_event_SliderClrLeft(lv_event_t * e);
extern lv_obj_t * ui_SliderClrLeft;
void ui_event_SliderClrCenter(lv_event_t * e);
extern lv_obj_t * ui_SliderClrCenter;
extern lv_obj_t * ui_LabelLeft;
extern lv_obj_t * ui_LabelCenter;
extern lv_obj_t * ui_LabelRight;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image7;
void ui_event_BtnStart(lv_event_t * e);
extern lv_obj_t * ui_BtnStart;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_GrpDynamics;
void ui_event_SliderClrVolume(lv_event_t * e);
extern lv_obj_t * ui_SliderClrVolume;
void ui_event_SliderClrSpeed(lv_event_t * e);
extern lv_obj_t * ui_SliderClrSpeed;
extern lv_obj_t * ui_LabelVolume;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_LabelColours;
extern lv_obj_t * ui_ImgFrameTopLeft;
extern lv_obj_t * ui_ImgFrameTopRight;
extern lv_obj_t * ui_LabelDynamics;
extern lv_obj_t * ui_ContainerFrameBotLeft;
extern lv_obj_t * ui_ImgFrameBottomLeft;
extern lv_obj_t * ui_ContainerFrameBotRight;
extern lv_obj_t * ui_ImgFrameBottomRight;
extern lv_obj_t * ui_LabelFX;
extern lv_obj_t * ui_ContainerFrameBotLeft1;
extern lv_obj_t * ui_ImgFrameBottomLeft1;
extern lv_obj_t * ui_ContainerFrameBotRight1;
extern lv_obj_t * ui_ImgFrameBottomRight1;
extern lv_obj_t * ui_ImageMenuPlayS1;
void ui_event_Container1(lv_event_t * e);
extern lv_obj_t * ui_Container1;
// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
extern lv_obj_t * ui_ScreenSetup;
extern lv_obj_t * ui_ImageBG;
void ui_event_BtnExit(lv_event_t * e);
extern lv_obj_t * ui_BtnExit;
extern lv_obj_t * ui_LabelReboot;
extern lv_obj_t * ui_PanelInfo;
extern lv_obj_t * ui_LabelInfoText;
extern lv_obj_t * ui_TopLabel2;
extern lv_obj_t * ui_ImageMenuSetupS2;
void ui_event_ContainerMenuPlayS2(lv_event_t * e);
extern lv_obj_t * ui_ContainerMenuPlayS2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_app_bg_png);    // assets/app_bg.png
LV_IMG_DECLARE(ui_img_color_bar_png);    // assets/color_bar.png
LV_IMG_DECLARE(ui_img_btn_play_inact_png);    // assets/btn_play_inact.png
LV_IMG_DECLARE(ui_img_btn_play_act_png);    // assets/btn_play_act.png
LV_IMG_DECLARE(ui_img_frame_left_png);    // assets/frame_left.png
LV_IMG_DECLARE(ui_img_frame_right_png);    // assets/frame_right.png
LV_IMG_DECLARE(ui_img_menu_play_on_png);    // assets/menu_play_on.png
LV_IMG_DECLARE(ui_img_btn_main_off_png);    // assets/btn_main_off.png
LV_IMG_DECLARE(ui_img_btn_main_on_png);    // assets/btn_main_on.png
LV_IMG_DECLARE(ui_img_menu_setup_on_png);    // assets/menu_setup_on.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
